// cmake template file, this file is generated by cmake, please don't edit it

#ifndef SERVER_FRAME_BUILD_FEATURE_H
#define SERVER_FRAME_BUILD_FEATURE_H

#pragma once

/* #undef SERVER_FRAME_ENABLE_LIBUUID */
#define SERVER_FRAME_ENABLE_GM_COMMAND 0
/* #undef SERVER_FRAME_VCS_COMMIT */
/* #undef SERVER_FRAME_VCS_VERSION */

#endif // SERVER_FRAME_BUILD_FEATURE_H
