

set(ATFRAMEWORK_LIBSHAPP_BASE_DIR ${CMAKE_CURRENT_LIST_DIR})
set (ATFRAMEWORK_LIBSHAPP_INC_DIR "${ATFRAMEWORK_LIBSHAPP_BASE_DIR}/include")
set (ATFRAMEWORK_LIBSHAPP_SRC_DIR "${ATFRAMEWORK_LIBSHAPP_BASE_DIR}/src")
set (ATFRAMEWORK_LIBSHAPP_LINK_NAME shapp)

include_directories(${ATFRAMEWORK_LIBSHAPP_INC_DIR})