

#ifndef ATFRAME_SERVICE_ATPROXY_LIBATPROXY_CLI_ATPROXY_BUILD_FEATURE_H
#define ATFRAME_SERVICE_ATPROXY_LIBATPROXY_CLI_ATPROXY_BUILD_FEATURE_H
# pragma once
#include "config/compile_optimize.h"
#if defined(ATPROXY_API_DLL) && ATPROXY_API_DLL
#define AT_PROXY_API UTIL_SYMBOL_EXPORT
#else
#define AT_PROXY_API
#endif

#endif //ATFRAME_SERVICE_ATPROXY_LIBATPROXY_CLI_ATPROXY_BUILD_FEATURE_H
